name: Reusable Workflow

on:
  workflow_call:
    inputs:
      env_name:
        description: 'Deployment environment'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Deployment environment'
        type: choice
        options:
          - dev
          - stg

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    steps:
      - name: Build application
        run: echo "Building application..."

  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    needs: build
    steps:
      - name: Run tests
        run: echo "Running tests..."
  other-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    needs: build
    steps:
      - name: Run tests
        run: echo "Running other tests with variable ${{ vars.OTHER_TEST_VARIABLE }}..."
  more-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    needs: build
    steps:
      - name: Run tests
        run: echo "Running more tests with secret ${{ secrets.MORE_TEST_SECRET }}..."

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    needs: 
      - test
      - other-test
      - more-test
    steps:
      - name: Deploy application
        run: echo "Deploying application..."
